repositoryUrl: git@github.com:UpHabit/semantic-release-jira-releases.git
branch: master
dryRun: false
debug: false
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/npm'
    - npmPublish: false
  - '@semantic-release/git'
  - - '@semantic-release/github'
    - failComment: false
