
name: Node.js CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: corepack enable && yarn
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn type-check
      - name: tesit
        run: yarn test

